Add python test for stickyness using a proxy.
web-servers/demo-webapp pull request #2
Opened 2024-11-13 16:03 UTC by jfclere

trying to reproduce https://issues.redhat.com/browse/JBCS-1856

2024-11-14 07:56 UTC, jajik requested changes
A few nitpicks.

Also, `is None` and `is not None` would be better than `== None` and `!= None`, but here it should not make a difference.

2024-11-14 07:56 UTC, jajik commented on test-demo-webapp.py
> +        continue
This can go

2024-11-14 07:56 UTC, jajik commented on test-demo-webapp.py
> +      result_queue.put((tid, 'failed'))
```python
result_queue.put((tid, 'done' if mydemo.request_response_loop(n) else 'failed'))
```

should work as well

2024-11-14 07:56 UTC, jajik commented on test-demo-webapp.py
> +    count = args[0]
Why not `int` even here?

2024-11-14 07:56 UTC, jajik commented on test-demo-webapp.py
> +    loop = int(args[1])
Also, maybe this would be cleaner

```python
if len(args) >= 1:
    count = int(args[0])
if len(args) == 2:
    loop = int(args[1])
```

2024-11-14 09:24 UTC, jfclere commented on test-demo-webapp.py
> +      result_queue.put((tid, 'failed'))
fixed

2024-11-14 09:24 UTC, jfclere commented on test-demo-webapp.py
> +    count = args[0]
fixed

2024-11-14 09:24 UTC, jfclere commented on test-demo-webapp.py
> +    loop = int(args[1])
fixed

2024-11-14 09:25 UTC, jajik submitted a review, later dismissed
Other than the one cast LGTM

2024-11-14 09:25 UTC, jajik commented on test-demo-webapp.py
>    for i in range(int(count)):
Here's still one cast redundant.

2024-11-14 11:27 UTC, jfclere commented
@jajik I have noted the thread keep running after one stopped, using daemon=True allows to stop all the threads, note the print()s in the thread cause:
Fatal Python error: _enter_buffered_busy: could not acquire lock for <_io.BufferedWriter name='<stdout>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0x00007f38843ce338)

so I remove them.

2024-11-14 11:34 UTC, jajik commented
> @jajik I have noted the thread keep running after one stopped, using daemon=True allows to stop all the threads, note the print()s in the thread cause: Fatal Python error: _enter_buffered_busy: could not acquire lock for <_io.BufferedWriter name=''> at interpreter shutdown, possibly due to daemon threads Python runtime state: finalizing (tstate=0x00007f38843ce338)
> 
> so I remove them.

Wouldn't flushing help?

```python
print(..., flush=True)
```

2024-11-14 13:11 UTC, jfclere commented
@jajik flush=True in the print()s doesn't help

2024-11-14 15:21 UTC, jfclere commented on test-demo-webapp.py
> +        continue
fixed

2024-11-19 08:54 UTC, jfclere commented
@jajik PR should be OK now ;-)

2024-11-19 09:03 UTC, merged